baseURL = "https://jzhao.xyz/"
languageCode = "en-us"
title = "Jacky Zhao | Personal Website"
googleAnalytics = "UA-148413215-1"

[params]
  headline = "jzhao.xyz"
  website = "https://jzhao.xyz"
  dateFormat = "2006-01-02"
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4